name: custom_platform_device_id
description: You can get device id from platform - linux/mac/windows/android/ios/web.
version: 1.0.8
homepage: https://github.com/amira-hossam99/custom_platform_device_id

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface: ^1.0.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.di1shuai.platform_device_id
        pluginClass: PlatformDeviceIdPlugin
      ios:
        pluginClass: PlatformDeviceIdPlugin


